import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import logo from '../../assets/logo.png';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF'
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    borderBottom: 1,
    borderBottomColor: '#C6A052',
    paddingBottom: 20
  },
  logo: {
    width: 120,
    marginRight: 20
  },
  title: {
    fontSize: 24,
    color: '#2C2C2C'
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginTop: 5
  },
  section: {
    marginBottom: 20
  },
  sectionTitle: {
    fontSize: 16,
    color: '#2C2C2C',
    marginBottom: 10,
    backgroundColor: '#F5F2E9',
    padding: 8
  },
  table: {
    display: 'table',
    width: '100%',
    marginBottom: 20
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomColor: '#EEEEEE',
    borderBottomWidth: 1,
    minHeight: 30,
    alignItems: 'center'
  },
  tableHeader: {
    backgroundColor: '#C6A052',
    color: '#FFFFFF'
  },
  tableCell: {
    flex: 1,
    padding: 8,
    fontSize: 10
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#666666',
    fontSize: 10,
    borderTop: 1,
    borderTopColor: '#EEEEEE',
    paddingTop: 10
  }
});

const ReportPDF = ({ data, type }) => {
  const formatDate = (date) => new Date(date).toLocaleDateString();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Image src={logo} style={styles.logo} />
          <View>
            <Text style={styles.title}>Analytics Report</Text>
            <Text style={styles.subtitle}>
              {type.charAt(0).toUpperCase() + type.slice(1)} Report - {formatDate(new Date())}
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Report Summary</Text>
          <Text>Total Records: {data.length}</Text>
          <Text>Report Type: {type}</Text>
          <Text>Generated On: {formatDate(new Date())}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Detailed Report</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              {Object.keys(data[0]).map((header, index) => (
                <Text key={index} style={styles.tableCell}>
                  {header.toUpperCase()}
                </Text>
              ))}
            </View>
            {data.map((row, rowIndex) => (
              <View key={rowIndex} style={styles.tableRow}>
                {Object.values(row).map((cell, cellIndex) => (
                  <Text key={cellIndex} style={styles.tableCell}>
                    {cell}
                  </Text>
                ))}
              </View>
            ))}
          </View>
        </View>

        <View style={styles.footer}>
          <Text>First Time Founder Capital - Confidential Report</Text>
          <Text>Generated by FTFC Analytics Platform</Text>
        </View>
      </Page>
    </Document>
  );
};

export default ReportPDF; 